# Data Manipulation



To start, we import the PyTorch library.
Note that the package name is `torch`

In [2]:
import torch

A tensor represents a (possibly multidimensional) array of numerical values

In [30]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [108]:
x = torch.arange(12, dtype=torch.float32)
x.shape

torch.Size([12])

In [6]:
x.numel()

12

We can access a tensor's *shape*

In [31]:
x.shape

torch.Size([12])

Change the shape of a tensor
without altering its size or values

In [109]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

We can construct a tensor with all elements set to 0
or one

In [38]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [39]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Sample each element randomly (and independently)

In [43]:
torch.randn(3, 4)

tensor([[ 0.5525, -0.6411, -1.4799,  0.3628],
        [-0.4125, -0.4854, -1.8241,  1.6716],
        [ 0.7574, -1.8448,  1.4159,  0.6300]])

Supplying the exact values for each element

In [61]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape
torch.tensor([[[1,2,3]]]).shape

torch.Size([1, 1, 3])

`[-1]` selects the last row and `[1:3]`(左闭右开)
selects the second and third rows

In [100]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

We can also *write* elements of a matrix by specifying indices

In [110]:
X[1, 2] = torch.tensor(9)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

To assign multiple elements the same value,
we apply the indexing on the left-hand side 
of the assignment operation

In [113]:
X[:4, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])

In [13]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [25]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

*concatenate* multiple tensors

In [115]:
X = torch.arange(12, dtype=torch.float32).reshape((2, 2, 3))
Y = torch.tensor([[[2.0, 1, 4], [1, 2, 3]], [[2.0, 1, 4], [1, 2, 3]]])
torch.cat((X, Y), dim=0).shape, torch.cat((X, Y), dim=0)

(torch.Size([4, 2, 3]),
 tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]],
 
         [[ 2.,  1.,  4.],
          [ 1.,  2.,  3.]],
 
         [[ 2.,  1.,  4.],
          [ 1.,  2.,  3.]]]))

Construct a binary tensor via *logical statements*

In [81]:
X == Y

tensor([[[False,  True, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]]])

Summing all the elements in the tensor

In [82]:
X.sum()

tensor(66.)

Perform elementwise binary operations
by invoking the *broadcasting mechanism*

In [34]:
a = torch.arange(18).reshape((3, 3, 2))
b = torch.arange(2).reshape((1, 2))
a, b, b.shape

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15],
          [16, 17]]]),
 tensor([[0, 1]]),
 torch.Size([1, 2]))

In [35]:
a + b

tensor([[[ 0,  2],
         [ 2,  4],
         [ 4,  6]],

        [[ 6,  8],
         [ 8, 10],
         [10, 12]],

        [[12, 14],
         [14, 16],
         [16, 18]]])

Running operations can cause new memory to be
allocated to host results

In [116]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Performing in-place operations

In [117]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140264609372656
id(Z): 140264609372656


If the value of `X` is not reused in subsequent computations,
we can also use `X[:] = X + Y` or `X += Y`
to reduce the memory overhead of the operation

In [120]:
before = id(X)
X += Y
id(X) == before

True

Converting to a NumPy tensor (`ndarray`)

In [122]:
A = X.numpy()
B = torch.from_numpy(A)
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Convert a size-1 tensor to a Python scalar

In [125]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

b = torch.tensor(3.0)
b, b.item(), float(b), int(b)

(tensor(3.), 3.0, 3.0, 3)